version: '3.4'

services:
  homework:
    image: ${DOCKER_REGISTRY-}homework
    build:
      context: .
      dockerfile: Homework/Dockerfile
    ports:
      - 4000:8080
    environment:
      - ConnectionStrings__Redis=redis:6379,password=p@ssw0rd
  redis:
    restart: always:latest
    container_name: redis
    image: redis:alpine
    command: redis-server --requirepass p@ssw0rd
    ports:
        - 6379:6379
    volumes:
        - /data/redis-data:/data
